api_platform:
    title: 'My API'
    version: '1.0.0'
    formats:
        json: ['application/json']
        html: ['text/html']
    mapping:
        paths: ['%kernel.project_dir%/src/ApiResource']
