# Init all database data.
# Update it if new init data scripts are added.
function project_init {
    composer install
    php /var/www/html/bin/console doctrine:migrations:migrate --no-interaction
}

source /var/www/html/config/docker/php/bash_aliases
