# Aliases
alias sf="/var/www/html/bin/console"
alias cc="/var/www/html/bin/console cache:clear"
alias ml="/var/www/html/bin/console doctrine:migrations:list --no-interaction"
alias mm="/var/www/html/bin/console doctrine:migrations:migrate --no-interaction"
alias md="/var/www/html/bin/console doctrine:migrations:diff --namespace=DoctrineMigrations"
alias mu="/var/www/html/bin/console doctrine:schema:update --force"
alias fxt="sf doctrine:fixtures:load --no-interaction --append"
alias int="project_init"